name: skycommands
description: Flutter SDK for SkyCommands — receive remote commands on production devices via Firebase Cloud Messaging and send results back to the backend.
version: 0.0.1
homepage: https://github.com/carum98/skycommands
repository: https://github.com/carum98/skycommands
issue_tracker: https://github.com/carum98/skycommands/issues

platforms:
  android:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^16.0.4
  flutter_udid: ^4.1.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
